// ── POSITIVO ─────────────────────────────────────────────────
const positivo = [

  // Qualidade geral
  "bom", "boa", "bons", "boas",
  "ótimo", "ótima", "ótimos", "ótimas",
  "excelente", "excelentes",
  "incrível", "incríveis",
  "maravilhoso", "maravilhosa", "maravilhosos", "maravilhosas",
  "perfeito", "perfeita", "perfeitos", "perfeitas",
  "fantástico", "fantástica", "fantásticos", "fantásticas",
  "espetacular", "espetaculares",
  "extraordinário", "extraordinária",
  "excepcional", "excepcionais",
  "magnífico", "magnífica",
  "sensacional", "sensacionais",
  "fenomenal", "fenomenais",
  "sublime", "sublimes",
  "primoroso", "primorosa",
  "impecável", "impecáveis",
  "irrepreensível", "irrepreensíveis",

  // Aprovação / curtir
  "gostei", "gosto", "adorei", "adoro", "amei", "amo",
  "curti", "curtir", "curtiu", "curtindo",
  "aprovei", "aprovo", "aprova",
  "gostoso", "gostosa", "gostosinho",
  "delicioso", "deliciosa", "deliciosos", "deliciosas",
  "saboroso", "saborosa",
  "agradável", "agradáveis",
  "prazeroso", "prazerosa",
  "satisfatório", "satisfatória",
  "satisfeito", "satisfeita",
  "contente", "contentes",

  // Entusiasmo / elogio
  "top", "tops",
  "demais", "indemais",
  "massa", "show", "dahora", "da hora",
  "animal", "foda", "fodástico",
  "insuportavelmente bom",
  "impressionante", "impressionantes",
  "surpreendente", "surpreendentes",
  "surpreendeu", "surpreendi",
  "uau", "wow", "nossa",

  // Felicidade / bem-estar
  "feliz", "felizes",
  "alegre", "alegres",
  "animado", "animada", "animados", "animadas",
  "empolgado", "empolgada",
  "entusiasmado", "entusiasmada",
  "radiante", "radiantes",
  "eufórico", "eufórica",
  "vibrante", "vibrantes",
  "encantado", "encantada",
  "encantador", "encantadora",
  "apaixonado", "apaixonada",
  "emocionado", "emocionada",
  "esperançoso", "esperançosa",
  "otimista", "otimistas",
  "positivo", "positiva",
  "bem-humorado", "bem-humorada",
  "tranquilo", "tranquila",
  "sereno", "serena",
  "calmo", "calma",
  "relaxado", "relaxada",

  // Sucesso / conquista
  "sucesso", "sucessos",
  "vitória", "vitórias",
  "venceu", "vencemos", "venceram",
  "ganhou", "ganhamos", "ganharam",
  "campeão", "campeã", "campeões",
  "triunfo", "triunfos",
  "triunfou", "triunfamos",
  "conquista", "conquistas",
  "conquistou", "conquistamos",
  "realizou", "realizei", "realizamos",
  "alcançou", "alcançamos",
  "atingiu", "atingimos",
  "superou", "superamos",
  "evoluiu", "evoluímos",
  "progresso", "avanço", "avanços",
  "crescimento", "cresceu",
  "melhora", "melhoria", "melhorou",
  "melhor", "melhores",
  "inovação", "inovador", "inovadora",
  "revolucionário", "revolucionária",

  // Recomendação
  "recomendo", "recomendo muito", "recomendo demais",
  "recomenda", "recomendado", "recomendada",
  "vale a pena", "vale muito a pena",
  "imperdível", "imperdíveis",
  "obrigatório", "obrigatória",
  "essencial", "essenciais",
  "indispensável", "indispensáveis",

  // Eficiência / competência
  "eficiente", "eficientes",
  "eficaz", "eficazes",
  "competente", "competentes",
  "profissional", "profissionais",
  "qualificado", "qualificada",
  "talentoso", "talentosa", "talentosos", "talentosas",
  "habilidoso", "habilidosa",
  "capaz", "capazes",
  "rápido", "rápida", "rápidos", "rápidas",
  "ágil", "ágeis",
  "prático", "prática",
  "funcional", "funcionais",
  "útil", "úteis",
  "confiável", "confiáveis",
  "seguro", "segura", "seguros", "seguras",
  "robusto", "robusta",
  "estável", "estáveis",
  "durável", "duráveis",
  "resistente", "resistentes",

  // Beleza / estética
  "bonito", "bonita", "bonitos", "bonitas",
  "lindo", "linda", "lindos", "lindas",
  "belo", "bela", "belos", "belas",
  "elegante", "elegantes",
  "gracioso", "graciosa",
  "estiloso", "estilosa",
  "moderno", "moderna",
  "sofisticado", "sofisticada",
  "requintado", "requintada",

  // Inovação / tecnologia
  "inovador", "inovadora",
  "tecnológico", "tecnológica",
  "avançado", "avançada",
  "inteligente", "inteligentes",
  "criativo", "criativa", "criativos", "criativas",
  "genial", "geniais",
  "brilhante", "brilhantes",
  "pioneiro", "pioneira",

  // Custo-benefício / acessibilidade
  "barato", "barata", "baratos", "baratas",
  "acessível", "acessíveis",
  "econômico", "econômica",
  "custo-benefício",
  "vantajoso", "vantajosa",
  "vale", "válido", "válida",
  "compensou", "compensar",
  "investimento", "bom investimento",
  "promoção", "desconto",
  "grátis", "gratuito", "gratuita",

  // Saúde / bem-estar
  "saudável", "saudáveis",
  "nutritivo", "nutritiva",
  "natural", "naturais",
  "orgânico", "orgânica",
  "energizante", "revitalizante",
  "revigorante",

  // Relacionamentos / comunidade
  "amigável", "amigáveis",
  "solidário", "solidária",
  "generoso", "generosa",
  "gentil", "gentis",
  "educado", "educada",
  "respeitoso", "respeitosa",
  "honesto", "honesta",
  "íntegro", "íntegra",
  "ético", "ética",
  "justo", "justa",
  "transparente", "transparentes",
  "empático", "empática",
  "carinhoso", "carinhosa",
  "amoroso", "amorosa",
  "dedicado", "dedicada",
  "comprometido", "comprometida",
  "responsável", "responsáveis",
  "confiante", "confiantes",

  // Entretenimento
  "divertido", "divertida", "divertidos", "divertidas",
  "engraçado", "engraçada",
  "hilário", "hilária",
  "emocionante", "emocionantes",
  "épico", "épica", "épicos", "épicas",
  "inesquecível", "inesquecíveis",
  "marcante", "marcantes",
  "impactante", "impactantes",
  "poderoso", "poderosa",
  "intenso", "intensa",
  "envolvente", "envolventes",
  "cativante", "cativantes",
  "inspirador", "inspiradora",
  "motivador", "motivadora",
  "edificante", "edificantes",
  "tocante", "tocantes",
  "comovente", "comoventes",

  // Expressões informais positivas (redes sociais)
  "top demais", "muito bom", "muito boa",
  "muito bem", "muito legal",
  "legal", "legais",
  "bacana", "bacanas",
  "gente boa", "pessoa incrível",
  "mandou bem", "mandou muito bem",
  "arrasou", "arrasar",
  "brilhou", "brilhar",
  "gabaritou",
  "acertou", "acertou em cheio",
  "foi demais", "ficou demais",
  "amando", "adorando",
  "maravilha", "que maravilha",
  "perfeição",
  "que show", "que incrível",
  "parabéns", "parabéns mesmo",
  "orgulho", "com orgulho",
  "faz bem", "ajuda muito",
  "surreal", "impossível não amar",
  "10/10", "nota 10", "nota máxima",
  "five stars", "cinco estrelas",
];

// ── NEGATIVO ─────────────────────────────────────────────────
const negativo = [

  // Qualidade geral
  "ruim", "ruins",
  "péssimo", "péssima", "péssimos", "péssimas",
  "horrível", "horríveis",
  "terrível", "terríveis",
  "lamentável", "lamentáveis",
  "deplorável", "deploráveis",
  "desastroso", "desastrosa",
  "catastrófico", "catastrófica",
  "calamitoso", "calamitosa",
  "execrável", "execráveis",
  "repugnante", "repugnantes",
  "asqueroso", "asquerosa",
  "nojento", "nojenta",
  "miserável", "miseráveis",

  // Rejeição / desgosto
  "odeio", "odiei", "ódio",
  "detesto", "detestei",
  "abomino", "abominei",
  "abominável", "abomináveis",
  "nojo", "que nojo",
  "repúdio",
  "antipatia",
  "não gosto", "não gostei",
  "não curti", "não curtiu",
  "não recomendo", "não recomendaria",
  "horrorizou",

  // Problemas / falhas
  "problema", "problemas",
  "erro", "erros",
  "falha", "falhas",
  "bug", "bugs",
  "defeito", "defeitos",
  "defeituoso", "defeituosa",
  "quebrado", "quebrada",
  "estragado", "estragada",
  "danificado", "danificada",
  "travou", "trava", "travando",
  "lento", "lenta", "lentos", "lentas",
  "demorado", "demorada",
  "instável", "instáveis",
  "inconsistente", "inconsistentes",
  "incompleto", "incompleta",
  "limitado", "limitada",
  "precário", "precária",
  "inadequado", "inadequada",

  // Decepção / frustração
  "decepcionante", "decepcionantes",
  "decepcionado", "decepcionada",
  "decepcionou", "decepcionaram",
  "frustrante", "frustrantes",
  "frustrado", "frustrada",
  "frustrou",
  "desapontante", "desapontantes",
  "desapontado", "desapontada",
  "desapontou",
  "chateado", "chateada",
  "irritante", "irritantes",
  "irritado", "irritada",
  "irritou",
  "chato", "chata",
  "maçante", "maçantes",
  "entediante", "entediantes",
  "tédio", "aborrecimento",
  "aborrecido", "aborrecida",

  // Tristeza / sofrimento
  "triste", "tristes",
  "tristeza",
  "sofrimento", "sofreu",
  "dor", "doloroso", "dolorosa",
  "angustiante", "angustiantes",
  "angústia", "ansiedade",
  "deprimido", "deprimida",
  "depressão",
  "desolado", "desolada",
  "desesperado", "desesperada",
  "desespero",
  "chorando", "chorei", "chorou",
  "lágrimas",
  "coração partido",
  "arrasado", "arrasada",
  "destruído", "destruída",

  // Fracasso / derrota
  "fracasso", "fracassos",
  "fracassou", "fracassamos",
  "falhou", "falhamos",
  "perdeu", "perdemos", "perderam",
  "derrota", "derrotas",
  "derrotado", "derrotada",
  "humilhante", "humilhantes",
  "humilhado", "humilhada",
  "humilhação",
  "vergonhoso", "vergonhosa",
  "vergonha",
  "fiasco", "fiascos",
  "desastre", "desastres",
  "catástrofe",
  "tragédia", "trágico", "trágica",

  // Reclamação / crítica
  "crise", "crises",
  "caos", "caótico", "caótica",
  "bagunça",
  "desorganizado", "desorganizada",
  "incompetente", "incompetentes",
  "despreparado", "despreparada",
  "ineficiente", "ineficientes",
  "ineficaz", "ineficazes",
  "inútil", "inúteis",
  "sem qualidade", "baixa qualidade",
  "mal feito", "mal feita",
  "irresponsável", "irresponsáveis",
  "negligente", "negligentes",
  "negligenciou",
  "descuidado", "descuidada",
  "desleixado", "desleixada",

  // Desonestidade / injustiça
  "mentira", "mentiras",
  "mentiu", "mentiroso", "mentirosa",
  "fraude", "fraudulento", "fraudulenta",
  "golpe", "golpista",
  "enganou", "enganar",
  "traição", "traiu",
  "hipócrita", "hipocrisia",
  "corrupto", "corrupção",
  "desonesto", "desonesta",
  "injusto", "injusta",
  "abuso", "abusivo", "abusiva",
  "exploração", "explorar",
  "manipulação", "manipulou",
  "manipulador", "manipuladora",

  // Medo / ameaça
  "medo", "com medo",
  "assustador", "assustadora",
  "aterrorizante", "aterrorizantes",
  "assustou", "assustante",
  "perigoso", "perigosa",
  "risco", "riscos",
  "ameaça", "ameaças",
  "ameaçou", "ameaçador",
  "preocupante", "preocupantes",
  "preocupado", "preocupada",
  "preocupação",
  "alarmante", "alarmantes",
  "inquietante", "inquietantes",

  // Violência / agressão
  "violência", "violento", "violenta",
  "agressão", "agressivo", "agressiva",
  "agrediu",
  "ataque", "atacou",
  "briga", "brigar",
  "conflito", "conflitos",
  "guerra", "guerras",
  "destruição", "destruiu",
  "vandalizou", "vandalismo",
  "crime", "crimes", "criminoso", "criminosa",

  // Saúde / doença
  "doença", "doenças",
  "doente", "doentes",
  "adoeceu", "adoeceu",
  "epidemia", "pandemia",
  "contaminação", "contaminado",
  "infectado", "infecção",
  "sintoma", "sintomas",
  "sofrimento", "agonia",
  "morte", "morreu", "mortes",
  "fatal", "fatais",
  "grave", "graves",

  // Custo / economia
  "caro", "cara", "caros", "caras",
  "absurdo", "absurda",
  "salgado", "salgada",
  "abusivo", "abusiva",
  "desperdício",
  "prejuízo", "prejuízos",
  "perdeu dinheiro",
  "jogou dinheiro fora",
  "cobrou demais",
  "superfaturamento",

  // Expressões informais negativas (redes sociais)
  "lixo", "uma lixo",
  "pior", "o pior", "a pior",
  "uma merda", "merda",
  "uma bosta", "bosta",
  "uma droga",
  "ridículo", "ridícula",
  "absurdo", "absurda",
  "escandaloso", "escandalosa",
  "inacreditável", "inacreditáveis",
  "inadmissível", "inadmissíveis",
  "inaceitável", "inaceitáveis",
  "lastimável", "lastimáveis",
  "vergonhoso", "vergonhosa",
  "patético", "patética",
  "lamentável",
  "deu ruim", "deu errado",
  "foi um fracasso",
  "terrível experiência",
  "horrenda experiência",
  "nunca mais", "jamais",
  "não volto", "não compro mais",
  "não uso mais",
  "evitem", "não façam isso",
  "fuja", "fujam",
  "zero estrelas", "0 estrelas",
  "nota zero", "0/10",
  "decepção total", "total decepção",
];

module.exports = { positivo, negativo };