const EMOCOES_LEXICON = {

  // ❤️ AMOR — vínculos afetivos, carinho, afeto romântico e familiar
  amor: {
    icon: '❤️',
    color: '#f43f5e',
    palavras: [
      // núcleo
      'amor', 'amo', 'amar', 'amei', 'amando',
      'adoro', 'adorei', 'adorar', 'adorando',
      'paixão', 'apaixonado', 'apaixonada', 'apaixonar',
      'apaixonei', 'apaixonou',
      // carinho e afeto
      'carinho', 'carinhoso', 'carinhosa',
      'afeto', 'afetivo', 'afetiva',
      'afetuoso', 'afetuosa',
      'ternura', 'ternamente',
      'meigo', 'meiga',
      'doce', 'doçura',
      'gentileza', 'gentil',
      // vínculos
      'querido', 'querida', 'quero muito', 'querer bem',
      'saudade', 'com saudade', 'matar saudade', 'saudoso', 'saudosa',
      'coração', 'meu coração', 'coração partido', 'de coração',
      'alma', 'alma gêmea',
      // gestos físicos de afeto
      'abraço', 'abraçar', 'abraçou', 'abraços',
      'beijo', 'beijar', 'beijou', 'beijos',
      'caricia', 'caríciar', 'aconchego',
      // família e pertencimento
      'família', 'família linda', 'minha família',
      'mãe', 'pai', 'filho', 'filha', 'irmão', 'irmã',
      'amigo', 'amiga', 'amizade', 'amigos',
      'companheiro', 'companheira', 'parceiro', 'parceira',
      'namorado', 'namorada', 'noivo', 'noiva',
      'marido', 'esposa', 'cônjuge',
      // romântico
      'romântico', 'romântica',
      'encanto', 'encantado', 'encantada', 'encantador', 'encantadora',
      'deslumbrado', 'deslumbrada',
      'fascinado', 'fascinada', 'fascinante',
      'idolatro', 'idolatria',
      'veneração', 'venero',
      'apego', 'apegado', 'apegada',
      'cumplicidade', 'cúmplice',
      'compaixão', 'compassivo', 'compassiva',
      'empatia', 'empático', 'empática',
      // expressões informais
      'te amo', 'amo muito', 'amo demais', 'amo você',
      'meu amor', 'meu bem', 'meu tudo', 'minha vida',
      'coração cheio', 'cheio de amor', 'cheia de amor',
      'com muito amor', 'feito com amor',
      'é tudo pra mim', 'não vivo sem',
      'apaixonei demais', 'morri de amores',
    ],
  },

  // 😄 ALEGRIA — felicidade, satisfação, entusiasmo, prazer
  alegria: {
    icon: '😄',
    color: '#f59e0b',
    palavras: [
      // estados emocionais
      'alegria', 'alegre', 'alegres',
      'feliz', 'felizes', 'felicidade',
      'contentamento', 'contente', 'contentes',
      'satisfação', 'satisfeito', 'satisfeita',
      'prazer', 'prazeroso', 'prazerosa',
      'bem-estar', 'bem estar',
      'euforia', 'eufórico', 'eufórica',
      'júbilo', 'jubiloso', 'jubilosa',
      'êxtase', 'extasiado', 'extasiada',
      'brilhante', 'radiante', 'radiantes',
      'encantado', 'encantada',
      'deslumbrado', 'deslumbrada',
      // entusiasmo e animação
      'animado', 'animada', 'animados', 'animadas',
      'empolgado', 'empolgada', 'empolgados', 'empolgadas',
      'entusiasmado', 'entusiasmada',
      'vibrando', 'vibrar', 'vibrei',
      'empolgação', 'empolgante',
      'excitado', 'excitada', 'excitante',
      'estimulado', 'estimulada',
      // qualidade / aprovação
      'ótimo', 'ótima', 'excelente', 'incrível',
      'maravilhoso', 'maravilhosa', 'perfeito', 'perfeita',
      'fantástico', 'fantástica', 'sensacional',
      'espetacular', 'fenomenal',
      'bom', 'boa', 'top',
      'gostei', 'amei', 'sucesso',
      'melhor', 'recomendo',
      // celebração
      'celebrar', 'celebrei', 'celebração',
      'comemorar', 'comemorei', 'comemoração',
      'festa', 'festivo', 'festiva', 'festejar',
      'vitória', 'venceu', 'campeão', 'campeã',
      'triunfo', 'conquista',
      'parabéns', 'felicitações',
      // expressões de riso e diversão
      'rindo', 'rir', 'risos', 'risada', 'gargalhada',
      'gargalhei', 'rir muito', 'morri de rir',
      'hahaha', 'kkk', 'kkkkk', 'rsrs', 'rs',
      'hilário', 'hilária', 'engraçado', 'engraçada',
      'divertido', 'divertida', 'diversão', 'divertir',
      'brincar', 'brincadeira', 'jogo',
      // otimismo e positividade
      'otimista', 'otimismo',
      'positivo', 'positiva', 'positividade',
      'esperança', 'esperançoso', 'esperançosa',
      'confiante', 'confiança', 'motivado', 'motivada',
      'inspirado', 'inspirada', 'inspiração',
      // bem-estar físico e tranquilidade
      'relaxado', 'relaxada', 'relaxar',
      'tranquilo', 'tranquila', 'tranquilidade',
      'sereno', 'serena', 'serenidade',
      'calmo', 'calma', 'paz', 'paz interior',
      'leveza', 'leve', 'liberto', 'liberta',
      // expressões informais / redes sociais
      'oba', 'uau', 'show', 'dahora', 'da hora',
      'incrível demais', 'maravilha', 'que maravilha',
      'amando a vida', 'que vida boa',
      'bom demais', 'muito bom', 'muito feliz',
      'na felicidade', 'felicidade demais',
      'que alegria', 'que delícia',
      'que gostoso', 'que gostosa',
      '😊', '😁', '😂', '🤣', '😍', '🥳',
    ],
  },

  // 😲 SURPRESA — espanto, choque, admiração, estupefação
  surpresa: {
    icon: '😲',
    color: '#8b5cf6',
    palavras: [
      // espanto positivo
      'surpresa', 'surpreso', 'surpresa',
      'surpreso', 'surpresa', 'surpreendente', 'surpreendentes',
      'surpreendeu', 'surpreendeu muito', 'me surpreendeu',
      'surpreendi', 'surpreender',
      'inesperado', 'inesperada',
      'não esperava', 'nunca esperava',
      'impressionante', 'impressionantes',
      'impressionou', 'me impressionou',
      'espantoso', 'espantosa', 'espanto',
      'espantou', 'fiquei espantado',
      'admirável', 'admiráveis', 'admiração',
      // intensidade
      'nossa', 'nossa senhora', 'meu deus', 'meu deus do céu',
      'uau', 'wow', 'caramba', 'caraio', 'caralho',
      'que isso', 'que foi isso', 'o quê',
      'sério', 'sério mesmo', 'é sério',
      'acredita', 'não acredito', 'não acredita',
      'inacreditável', 'inacreditáveis',
      'impossível', 'como assim',
      'que absurdo', 'absurdo',
      // choque
      'chocante', 'chocantes', 'chocou', 'fiquei chocado',
      'chocado', 'chocada',
      'atordoado', 'atordoada',
      'perplexo', 'perplexa', 'perplexos', 'perplexas',
      'perplexidade',
      'pasmo', 'pasma', 'pasmado', 'pasmada',
      'boquiaberto', 'boquiaberta',
      'sem palavras', 'sem ação', 'travei',
      'caiu meu queixo',
      'não acreditei', 'não acreditou',
      'tomei um susto', 'tomou um susto',
      'susto', 'assustou', 'assustar',
      // admiração
      'admirado', 'admirada',
      'encantado', 'encantada',
      'maravilhado', 'maravilhada',
      'deslumbrado', 'deslumbrada',
      'estupefato', 'estupefata',
      'assombrado', 'assombrada', 'assombroso', 'assombrosa',
      'de queixo caído',
      // revelação / descoberta
      'revelação', 'revelador', 'reveladora',
      'descoberta', 'descubra', 'descobri',
      'inesperadamente', 'de repente',
      'nunca imaginei', 'jamais imaginaria',
      'quem diria', 'quem imaginava',
      'virada', 'reviravolta',
      // expressões informais
      'que surpresa', 'que choque', 'que susto',
      '😮', '😯', '😱', '🤯', '😲',
    ],
  },

  // 😨 MEDO — ansiedade, terror, insegurança, pavor
  medo: {
    icon: '😨',
    color: '#06b6d4',
    palavras: [
      // medo e terror
      'medo', 'com medo', 'cheio de medo', 'cheia de medo',
      'terror', 'aterrorizado', 'aterrorizada',
      'aterrorizante', 'aterrorizantes',
      'horripilante', 'horripilantes',
      'assustador', 'assustadora',
      'assustado', 'assustada',
      'assustou', 'assustar',
      'susto', 'tomei susto',
      'pavor', 'pavoso', 'pavosa',
      // pânico e ansiedade
      'pânico', 'em pânico', 'entrei em pânico',
      'ansiedade', 'ansioso', 'ansiosa',
      'angústia', 'angustiante', 'angustiado', 'angustiada',
      'apreensão', 'apreensivo', 'apreensiva',
      'nervoso', 'nervosa', 'nervosismo',
      'tenso', 'tensa', 'tensão',
      'estressado', 'estressada', 'estresse',
      'agitado', 'agitada', 'agitação',
      'inquieto', 'inquieta', 'inquietação',
      'preocupado', 'preocupada', 'preocupação',
      'alarmado', 'alarmada', 'alarmante',
      // ameaça e perigo
      'ameaça', 'ameaças', 'ameaçador', 'ameaçadora',
      'ameaçou', 'ameaçando',
      'risco', 'riscos', 'arriscado', 'arriscada',
      'perigoso', 'perigosa', 'perigo', 'em perigo',
      'vulnerável', 'vulneráveis',
      'exposto', 'exposta',
      'desprotegido', 'desprotegida',
      'inseguro', 'insegura', 'insegurança',
      // reações físicas ao medo
      'tremendo', 'tremer', 'tremor',
      'gelado', 'gelada', 'ficou gelado',
      'arrepio', 'arrepios', 'arrepiou',
      'coração acelerado', 'coração disparado',
      'suor frio',
      'respiração acelerada',
      'fobia', 'fóbico', 'fóbica',
      'trauma', 'traumatizado', 'traumatizada', 'traumatizante',
      // pesadelos e horror
      'pesadelo', 'pesadelos',
      'horrendo', 'horrenda',
      'horroroso', 'horrorosa', 'horror',
      'sinistro', 'sinistra',
      'macabro', 'macabra',
      'perturbador', 'perturbadora', 'perturbante',
      'arrepiante', 'arrepiantes',
      // desconforto / hesitação
      'receoso', 'receosa', 'receio',
      'hesitante', 'hesitar', 'hesitei',
      'desconfiado', 'desconfiada', 'desconfiança',
      'paranoia', 'paranoico', 'paranoica',
      'desconfio', 'desconfiei',
      // expressões informais
      'me apavorou', 'me assustou muito',
      'quase morri do coração',
      'fiquei sem chão',
      'não dormi de medo',
      '😨', '😰', '😱', '🥶', '😟',
    ],
  },

  // 😡 RAIVA — indignação, revolta, irritação, fúria
  raiva: {
    icon: '😡',
    color: '#ef4444',
    palavras: [
      // raiva e ira
      'raiva', 'com raiva', 'cheio de raiva',
      'ódio', 'odeio', 'odiei', 'odiar',
      'fúria', 'furioso', 'furiosa',
      'irado', 'irada',
      'bravo', 'brava',
      'irritado', 'irritada', 'irritação', 'irritante',
      'irritou', 'irritar',
      'exasperado', 'exasperada',
      'exaltado', 'exaltada',
      'transtornado', 'transtornada',
      // revolta e indignação
      'revoltante', 'revoltantes',
      'revoltado', 'revoltada', 'revolta',
      'revoltou', 'revoltar',
      'indignado', 'indignada', 'indignação',
      'indignante', 'indignantes',
      'indignou', 'indignar',
      'absurdo', 'absurda',
      'inadmissível', 'inadmissíveis',
      'inaceitável', 'inaceitáveis',
      'intolerável', 'intoleráveis',
      // vergonha e crítica moral
      'vergonhoso', 'vergonhosa', 'vergonha',
      'desonra', 'desonrado', 'desonrada',
      'escândalo', 'escandaloso', 'escandalosa',
      'ultrajante', 'ultrajantes', 'ultraje',
      'deplorável', 'deploráveis',
      'lamentável', 'lamentáveis',
      'reprovável', 'reprovar',
      'repudio', 'repúdio',
      // qualidade negativa que gera raiva
      'horrível', 'terrível', 'péssimo', 'péssima',
      'ridículo', 'ridícula', 'ridículos', 'ridículas',
      'estúpido', 'estúpida', 'estupidez',
      'idiota', 'idiotas', 'idiota mesmo',
      'imbecil', 'imbecis',
      'burrice', 'burro', 'burra',
      'palhaçada', 'palhaço', 'palhaça',
      'piada', 'piada de mau gosto',
      'inadmissível', 'que absurdo',
      // expressões de revolta fortes
      'que merda', 'merda',
      'que bosta', 'bosta',
      'que lixo', 'lixo',
      'que droga',
      'vai se ferrar', 'vai tomar',
      'tô com raiva', 'to com raiva',
      // desrespeito e agressão
      'desrespeitoso', 'desrespeitosa', 'desrespeito',
      'ofensivo', 'ofensiva', 'ofensa',
      'ofendido', 'ofendida', 'ofendeu',
      'humilhante', 'humilhantes',
      'humilhado', 'humilhada', 'humilhação',
      'agressivo', 'agressiva', 'agressão',
      'grosseiro', 'grosseira', 'grosseria',
      'rude', 'rudes',
      // injustiça
      'injusto', 'injusta', 'injustiça',
      'injustiçado', 'injustiçada',
      'discriminação', 'discriminado', 'discriminada',
      'preconceito', 'preconceituoso', 'preconceituosa',
      'racismo', 'racista',
      'exploração', 'explorado', 'explorada',
      'manipulação', 'manipulado', 'manipulada',
      'golpe', 'golpismo', 'golpista',
      'traição', 'traiu', 'traidor', 'traidora',
      // expressões informais
      'me tirou do sério', 'tirou o sério',
      'me deixou louco', 'me deixou louca',
      'ferveu meu sangue', 'sangue fervendo',
      'não aguento mais', 'chega',
      'já encheu', 'enche o saco',
      '😡', '🤬', '😤', '😠', '👿',
    ],
  },

  // 😢 TRISTEZA — melancolia, perda, desânimo, solidão
  tristeza: {
    icon: '😢',
    color: '#64748b',
    palavras: [
      // tristeza central
      'triste', 'tristes', 'tristeza',
      'melancólico', 'melancólica', 'melancolia',
      'infeliz', 'infelizes', 'infelicidade',
      'abatido', 'abatida', 'abatimento',
      'desolado', 'desolada', 'desolação',
      'entristecido', 'entristecida',
      'entristeceu', 'entristeceu muito',
      // choro e dor emocional
      'choro', 'chorei', 'chorando', 'chorar', 'chorou',
      'lágrima', 'lágrimas', 'lacrimejar',
      'soluço', 'soluçar',
      'pranteio', 'prantear',
      'dor', 'doloroso', 'dolorosa',
      'angústia', 'angustiado', 'angustiada',
      'sofrimento', 'sofreu', 'sofrer',
      'padecimento', 'padecer',
      // decepção e frustração
      'decepção', 'decepcionante', 'decepcionantes',
      'decepcionado', 'decepcionada',
      'decepcionou', 'decepcionar',
      'frustração', 'frustrado', 'frustrada',
      'frustrante', 'frustrantes', 'frustrou',
      'desapontado', 'desapontada', 'desapontamento',
      'desapontante', 'desapontou',
      'chateado', 'chateada', 'chatear',
      'magoado', 'magoada', 'mágoa', 'magoou',
      // perda e luto
      'perda', 'perdido', 'perdida',
      'luto', 'enlutado', 'enlutada',
      'saudade', 'com saudade', 'saudoso', 'saudosa',
      'falta', 'faz falta', 'sinto falta',
      'ausência', 'ausente',
      'solidão', 'sozinho', 'sozinha',
      'abandonado', 'abandonada', 'abandono',
      'esquecido', 'esquecida',
      'negligenciado', 'negligenciada',
      // desânimo e desesperança
      'desânimo', 'desanimado', 'desanimada',
      'desanimou', 'desanimar',
      'desmotivado', 'desmotivada',
      'desesperançado', 'desesperançada',
      'desesperança',
      'sem esperança', 'perdeu a esperança',
      'resignado', 'resignada', 'resignação',
      'conformado', 'conformada',
      // depressão e exaustão emocional
      'deprimido', 'deprimida', 'depressão',
      'deprê', 'na baixa',
      'vazio', 'vazia', 'vazio interior',
      'numb', 'entorpecido', 'entorpecida',
      'sem ânimo', 'sem energia', 'apático', 'apática',
      'indiferente', 'distante',
      'cansado emocionalmente', 'esgotado', 'esgotada',
      'exausto', 'exausta', 'exaustão emocional',
      // fracasso e vergonha pessoal
      'fracasso', 'fracassou', 'fracassado', 'fracassada',
      'falhou', 'falha',
      'pior', 'o pior', 'a pior',
      'lamentável', 'culpado', 'culpada', 'culpa',
      'arrependido', 'arrependida', 'arrependimento',
      'peso na consciência', 'remorso',
      // expressões informais
      'coração partido', 'partido',
      'destruído por dentro', 'destruída por dentro',
      'arrasado', 'arrasada',
      'no fundo do poço',
      'não tô bem', 'não estou bem',
      'tô mal', 'to mal',
      'difícil demais', 'pesado demais',
      'não aguento mais',
      '😢', '😭', '😔', '😞', '💔',
    ],
  },

  // 🤢 NOJO — repulsa, aversão, repugnância, asco
  nojo: {
    icon: '🤢',
    color: '#84cc16',
    palavras: [
      // nojo central
      'nojo', 'com nojo', 'que nojo',
      'nojo', // erro ortográfico comum em redes sociais
      'enjoado', 'enjoada', 'enjoar', 'enjoou',
      'asco', 'asqueroso', 'asquerosa',
      'repulsa', 'repulsivo', 'repulsiva',
      'repugnante', 'repugnância', 'repugnar',
      // podridão e sujeira
      'podre', 'podres', 'podridão',
      'sujo', 'suja', 'sujos', 'sujas', 'sujeira',
      'imundo', 'imunda', 'imundice', 'imundície',
      'fedorento', 'fedorenta', 'fedido', 'fedor', 'fede',
      'cheiroso', 'cheiro ruim', 'cheiro horrível',
      'malcheiroso', 'malcheirosa',
      'podre demais',
      // aspecto físico desagradável
      'grotesco', 'grotesca',
      'repelente', 'repelentes',
      'repulsante',
      'nauseante', 'nauseantes', 'nausea', 'náusea',
      'aversão', 'aversões',
      'indigesto', 'indigesta',
      'rancoroso', 'rancorosa', 'ranço',
      // ética e moral
      'degradante', 'degradantes',
      'deprimente', 'deprimentes',
      'humilhante', 'humilhantes',
      'reprovável',
      'vergonhoso', 'vergonhosa',
      'imoral', 'imorais',
      'sem vergonha', 'safado', 'safada', 'safadeza',
      'baixo', 'baixa', 'baixaria',
      'nojento', 'nojenta', 'nojentos', 'nojentas',
      'repudiável', 'inadmissível',
      'escrotidão', 'escroto', 'escrota',
      'que horror', 'horroroso', 'horrorosa',
      // reações físicas
      'vômito', 'vomitei', 'vomitar', 'vomitou',
      'engasgou', 'engasgar',
      'arrepiou', 'deu arrepio',
      'estômago embrulhado', 'estômago virou',
      'me deu nojo', 'me causou nojo',
      // expressões informais
      'que nojinho', 'nojinho',
      'eca', 'blergh', 'argh',
      'nojento demais', 'horrendo demais',
      'repulsivo demais', 'insuportável',
      '🤢', '🤮', '😷', '🤧', '🙁',
    ],
  },

  // 🤩 ANTECIPAÇÃO — expectativa, curiosidade, ansiedade positiva, desejo
  antecipacao: {
    icon: '🤩',
    color: '#f97316',
    palavras: [
      // expectativa e espera
      'expectativa', 'na expectativa', 'cheio de expectativa',
      'aguardando', 'aguardar', 'aguardei',
      'esperando', 'esperar', 'esperei',
      'ansioso', 'ansiosa', 'ansiosamente',
      'ansiedade positiva',
      'mal posso esperar', 'mal posso aguardar',
      'não vejo a hora', 'quando vai sair',
      'não aguento de curiosidade',
      // curiosidade
      'curioso', 'curiosa', 'curiosidade',
      'quero saber', 'quero ver', 'quero descobrir',
      'quero conhecer', 'preciso saber',
      'me conta', 'como vai ser',
      'vontade de ver', 'vontade de saber',
      // lançamento / novidade
      'lançamento', 'lançamentos',
      'novidade', 'novidades',
      'estreia', 'estreou', 'vai estrear',
      'vem aí', 'vem por aí',
      'em breve', 'brevemente',
      'quando sai', 'quando lança', 'quando chega',
      'data de lançamento', 'data de saída',
      'pré-lançamento', 'pré-venda',
      'já tá disponível', 'liberou',
      // planejamento e futuro
      'futuro', 'futuramente',
      'próximo', 'próxima', 'próximos', 'próximas',
      'tendência', 'tendências',
      'inovação', 'inovador', 'inovadora',
      'revolução', 'revolucionário', 'revolucionária',
      'promissor', 'promissora',
      'promete muito', 'parece incrível',
      'vai ser incrível', 'vai ser épico',
      // desejo e vontade
      'quero', 'quero muito', 'quero demais',
      'desejo', 'desejando', 'desejei',
      'sonho', 'sonhando', 'sonhei',
      'wishlist', 'lista de desejos',
      'cobiçado', 'cobiçada', 'cobiça',
      'almejado', 'almejada', 'almejar',
      'preciso disso', 'preciso ter',
      'já quero', 'já quero muito',
      // planejamento de evento
      'contagem regressiva', 'faltam dias',
      'preparando', 'me preparando',
      'planejando', 'planos',
      'cronograma',
      // hype e agitação social
      'hype', 'muito hype', 'tá gerando hype',
      'viral', 'viralizou', 'viralizar',
      'aguardado', 'aguardada', 'mais aguardado',
      'mais esperado', 'mais esperada',
      'todo mundo falando',
      'buzz', 'todo mundo quer',
      'na boca do povo', 'trending',
      // expressões informais
      'tô ansioso', 'to ansioso',
      'tô no hype', 'tô esperando',
      'já quero na minha mão',
      'quando abre o link',
      'quero muito assistir', 'quero muito jogar',
      '🤩', '🥳', '😍', '🙌', '👀', '🔥',
    ],
  },

};